<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Condominio\Module'                        => __DIR__ . '/Module.php',
    'Condominio\Controller\IndexController' => __DIR__ . '/src/Condominio/Controller/IndexController.php',
    'Condominio\Controller\LoginController' => __DIR__ . '/src/Condominio/Controller/LoginController.php',
    'CondominioTest\Framework\TestCase'        => __DIR__ . '/tests/Condominio/Framework/TestCase.php',
    'CondominioTest\SampleTest'                => __DIR__ . '/tests/Condominio/SampleTest.php',
    'Condominio\Model\Usuarios'                      => __DIR__ . '/Model/Usuarios.php',
    'Condominio\Model\Unidades'                      => __DIR__ . '/Model/Unidades.php',
);
