<div>
    <h2>Unidades</h2>
    <div class="ferramentas">
        <a href="<?php echo $this->url('condominio') ?>/unidades/add">Adicionar</a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <td>#</td>
            <td>Unidade</td>
            <td>Ações</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->dados as $dado): ?>
        <tr>
            <td><?php echo $dado->getIdUnidades(); ?></td>
            <td>
            	<?php echo $dado->getUnidade(); ?>
			</td>
            <td>
            	<a href="<?php echo $this->url('condominio') ?>/unidades/edit/<?php echo $dado->getIdUnidades(); ?>">Editar</a>
            	<a href="<?php echo $this->url('condominio') ?>/unidades/delete/<?php echo $dado->getIdUnidades(); ?>" class="apagar">Apagar</a>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$(".apagar").click(function(){
		if(confirm('Tem certeza?')){
			return true;
		} else {
			return false;
		}
	});
});
</script>